version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ledgex_password
      POSTGRES_USER: ledgex_user
      POSTGRES_DB: ledgex_dev
