name: API workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Elixir Server
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: "1.15.2"
          otp-version: "26.0"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-.txt
      - name: Install dependencies
        run: |
          cd server
          mix deps.get
      - name: Run tests and collect coverage
        run: pytest --cov=api.calculator --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          flags: server
          files: server/cover/excoveralls.json
          token: ${{ secrets.CODECOV_TOKEN }}
