name: API workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Elixir Server
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ledgex_password
          POSTGRES_USER: ledgex_user
          POSTGRES_DB: ledgex_dev
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@980f47ea52afa4c3bf2a68d5a90051b7bb60f09c
        with:
          elixir-version: "1.15.2"
          otp-version: "26.0"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-.txt
      - name: Install dependencies
        run: |
          cd server
          mix deps.get
      - name: Run tests and collect coverage
        run: |
          cd server
          mix coveralls.json
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4
        with:
          flags: server
          files: server/cover/excoveralls.json
          token: ${{ secrets.CODECOV_TOKEN }}
